### ISSUE TITLE
Could you share your code now?

### ISSUE THREAD

**Issue by Conearth** [albertszg/MbandWaveletNet#1]
Hi! 
The paper has been published and it's a great work! Could you share your code now?
Many thanks!

**Comment by albertszg** [comment]
I'm sorry that it's still under review. The work you see may not be this work.

**Comment by albertszg** [comment]
By the way, could you please provide the pubulised paper information?

**Comment by Conearth** [comment]
> By the way, could you please provide the pubulised paper information?

Sure. The title is "Multiscale Wavelet Graph AutoEncoder for
Multivariate Time-Series Anomaly Detection
"

**Comment by albertszg** [comment]
This repository is for "M-band Wavelet Network for Machine Anomaly Detection from a Frequency Perspective"
